spring:
  application:
    name: chat

  datasource:
    url: jdbc:postgresql://dpg-d6du8gfgi27c738n42u0-a.oregon-postgres.render.com:5432/health_db_kxmb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  data:
    redis:
      url: ${REDIS_URL}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: ${PORT:8080}